[package]
name = "buttercup"
version = "0.1.0"
authors = ["psgliniecki <psgliniecki@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2"
actix-rt = "1"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = {version = "1.*", features = ["preserve_order"]}
chrono = {version = "0.4", features = ["serde"]}
chrono-tz = {version ="0.5", features = ["serde"]}
tz-search = "0.1"
strum = "0.18.0"
strum_macros = "0.18.0"
num = {version="0.2.*", features = ["serde"]}
num-rational = "0.2"
sunrise = "1.0.0"
url = "2"
isolang = {version = "1", features = ["serde_serialize"]}
isocountry = "0.2"
publicsuffix = "1.5"
lazy_static = "1"
fast_chemail = "0.9"
gstreamer = "0.15.4"
dashmap = "3.11"