[package]
name = "buttercup"
version = "0.1.0"
authors = ["psgliniecki <psgliniecki@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.*"
actix-rt = "1.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.*"
chrono = "0.4.*"
strum = "0.18.0"
strum_macros = "0.18.0"
num = "0.2.*"