[package]
name = "buttercup"
version = "0.1.0"
authors = ["psgliniecki <psgliniecki@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2"
actix-rt = "1"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = {version = "1.*", features = ["preserve_order"]}
chrono = "0.4"
chrono-tz = "0.5"
tz-search = "0.1"
strum = "0.18.0"
strum_macros = "0.18.0"
num = "0.2.*"
sunrise = "1.0.0"
url = "2"

[dev-dependencies]
maplit = "1"